version: "3.8"
services:
  # redis:
  #   image: 'redis:alpine'
  #   container_name: redis_c
  #   networks:
  #     - app-network

  websocket:
    build: ./webSocket
    container_name: websocket_c
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - twilioAccountSid=${twilioAccountSid}
      - twilioAuthToken=${twilioAuthToken}
      - mongooseURL=${mongooseURL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}  
      - accessKeyId=${accessKeyId}
      - secretAccessKey=${secretAccessKey}
      - BUCKET=${BUCKET}
      - DEFAULT_EXPIRATION=${DEFAULT_EXPIRATION}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - SERVER_URL=${SERVER_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - CDN_URL=${CDN_URL}
      - elasticache=${elasticache}
  backend:
    build: ./server
    container_name: backend_c
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - twilioAccountSid=${twilioAccountSid}
      - twilioAuthToken=${twilioAuthToken}
      - mongooseURL=${mongooseURL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}  
      - accessKeyId=${accessKeyId}
      - secretAccessKey=${secretAccessKey}
      - BUCKET=${BUCKET}
      - DEFAULT_EXPIRATION=${DEFAULT_EXPIRATION}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - SERVER_URL=${SERVER_URL}
      - CDN_URL=${CDN_URL}
      - elasticache=${elasticache}
    # volumes:
    #   - ./server:/usr/src/app

  # frontend:
  #   build: 
  #     context: ./my-app
  #     dockerfile: Dockerfile.dev
  #   container_name: frontend_c
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   # volumes:
  #     # - ./my-app:/usr/src/app
  #     # - node_modules:/usr/src/app/node_modules/
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_API_URL=${REACT_APP_API_URL}
  #     - REACT_APP_TF_MODEL_URL=${REACT_APP_TF_MODEL_URL}

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx_c
    volumes:
      - ./nginx/cert:/etc/ssl
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
networks:
  app-network:
    name: Meeting
volumes:
  node_modules:
