version: "3.8"
services:
  redis:
    image: 'redis:alpine'
    container_name: redis_c
    networks:
      - app-network
  backend:
    build: ./server
    container_name: backend_c
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - twilioAccountSid=${twilioAccountSid}
      - twilioAuthToken=${twilioAuthToken}
      - mongooseURL=${mongooseURL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}  
      - accessKeyId=${accessKeyId}
      - secretAccessKey=${secretAccessKey}
      - BUCKET=${BUCKET}
      - DEFAULT_EXPIRATION=${DEFAULT_EXPIRATION}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - SERVER_URL=${SERVER_URL}

    # volumes:
    #   - ./server:/usr/src/app

  # frontend:
  #   build: 
  #     context: ./my-app
  #     dockerfile: Dockerfile.prod
  #   container_name: frontend_c
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  #   # volumes:
  #   #   - ./my-app:/usr/src/app
  #   environment:
  #     - NODE_ENV=production 

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx_c
    volumes:
      - ./nginx/cert:/etc/ssl
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
networks:
  app-network:
    name: Meeting

