version: "3.8"
services:
    backend:
        build: ./server
        container_name: backend_c
        ports:
            - "5000:5000"
        networks:
            - app-network
        environment:
          - twilioAccountSid=${twilioAccountSid}
          - twilioAuthToken=${twilioAuthToken}

    frontend:
        build: ./my-app
        container_name: frontend_c
        ports:
            - "3000:3000"
        networks:
            - app-network

    nginx:
        restart: always
        build: ./nginx
        container_name: nginx_c
        volumes:
            - ./nginx/cert:/etc/ssl
        ports:
            - '80:80'
            - '443:443'
        networks:
            - app-network
networks:
  app-network:
    name: Meeting
        
