---
name: Build and Deploy React App to CloudFront
on:
  push:
    branches: [develop]
env:
  REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: jaywang-project.com
      DIST: build
      REGION: us-east-1
      DIST_ID: E2PGQ5JTP0MU7G

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: /home/runner/work/Meeting/Meeting/my-app/
        run: |
          node --version
          npm install
          npm ci --production

      - name: Build Static Website
        working-directory: /home/runner/work/Meeting/Meeting/my-app/
        run: |
          CI=false npm run build

      - name: Copy files to the production website with the AWS CLI
        working-directory: /home/runner/work/Meeting/Meeting/my-app/
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

      - name: clean cloudfront cache
        working-directory: /home/runner/work/Meeting/Meeting/my-app/
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DIST_ID }} \
            --paths "/*"
